version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  todo-app:
    build: .
    container_name: todo-container
    depends_on:
      postgres:
        condition: service_healthy  # Czekamy, aż PostgreSQL będzie gotowy
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/todo_db
    ports:
      - "5000:5000"  # MAPPING PORTU DLA FLASKA
    stdin_open: true
    tty: true

  postgres:
    image: postgres:14
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d todo_db"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
