global:
  scrape_interval: 5s  # Co 5 sekund pobieramy metryki

scrape_configs:
  - job_name: "flask_app"
    static_configs:
      - targets: ["todo-app:5000"]  # Pobieramy metryki z naszej aplikacji Flask
